articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/detail', views.detail, name='detail'),

    path('create/', views.create, name='create'),

    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),

    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
    # => articles/10/comments/5/delete/
]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    # comment_set =

class Comment(models.Model):
    # id =
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE) # 연결된 article이 삭제될 때 관련된 comment가 다 삭제되는 것
    # article_id =

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = '__all__'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'

        # fields => 추가할 필드 이름 목록
        # fields = ('content', )

        # excludes => 제외할 필드 이름 목록
        exclude = ('article', )

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('articles:index')

    else:
        form = ArticleForm()

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)



def detail(request, id):
    article = Article.objects.get(id=id)
    comment_form = CommentForm()

    # comment 목록 조회
    # 첫번째 방법
    # comment_list = Comment.objects.filter(article=article)  # 앞 article: class에 있는 article / 뒤 article: 위에 있는 article

    # 두번째 방법
    # comment_list = article.comment_set.all()

    # 세번째 방법
    # html 코드에서 article.comment_set.all로 사용

    context = {
        'article': article,
        'comment_form': comment_form,
        # 'comment_list' : comment_list,
    }

    return render(request, 'detail.html', context)


def comment_create(request, article_id):
    # 사용자가 입력한 정보를 form에 입력
    comment_form = CommentForm(request.POST)

    # 유효성 검사
    if comment_form.is_valid():
        # form을 저장 => 추가로 넣어야 하는 데이터를 넣기 위해 저장 멈춰!
        comment = comment_form.save(commit=False)  # 잠깐 실행하지 않고 멈추는 것

        # 첫번째 방법
        # # article_id를 기준으로 article obj를 가져와서
        # article = Article.objects.get(id=article_id)
        # # article 컬럼에 추가
        # comment.article = article          # 객체 자체를 넣는 방법

        # 두번째 방법
        comment.article_id = article_id      # 아이디를 넣는 방법


        # 저장
        comment.save()

        return redirect('articles:detail', id=article_id)


def comment_delete(request, article_id, id):
    comment = Comment.objects.get(id=id)

    comment.delete()

    return redirect('articles:detail', id=article_id)

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}

  <h1>{{article.title}}</h1>
  <p>{{article.content}}</p>

  <hr>
  <!-- hr: 밑에 선 -->
  <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
    {% csrf_token %}
    {{comment_form}}
    <input type="submit">
  </form>

  <!-- if not len(article.comment_set.all()) -->
  {% if not article.comment_set.all|length %}
    <p>댓글이 없습니다.</p>
  {% endif %}

  <!-- 세번째 방법: 바로 html에 써서 호출하는 것 / 두번째 방법 전에는 for comment in comment_list-->
  <!-- 두번째 방법은 comment_list = article.comment_set.all() 이므로-->
  {% for comment in article.comment_set.all %}
    <p>
      {{comment.content}} 
      <a href="{% url 'articles:comment_delete' article_id=article.id id=comment.id %}">삭제</a> 
    </p> 

  {% endfor %}


{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}

  <form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
  </form>

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}


  {% for article in articles %}
    <p>{{article.title}}</p>
    <!-- detail 클릭했을 때 id를 선택하지 못하고 서버가 고정시키는 것 -->
    <a href="{% url 'articles:detail' id=article.id %}">detail</a>
    <hr>

  {% endfor %}


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <a href="{% url 'articles:index' %}">Home</a>
  <a href="{% url 'articles:create' %}">Create</a>
  


  {% block body %}

  {% endblock %}
</body>
</html>